### ISSUE TITLE
log does not view logs consequently

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/verticed#205]

**Comment by indykish** [comment]
@rajthilakmca  Good work, in find the UTF8 issue.
Check this out.
http://rosettacode.org/wiki/Strip_control_codes_and_extended_characters_from_a_string#Go

As this is used in both `gulp` and `megamd `, it would better to put in `libgo - fs package`

**Comment by indykish** [comment]
https://github.com/megamsys/vertice/pull/782
